// THROWAWAY SPIKE (bd-sjb4pzx8) — the round-trip feasibility oracle.
//   qmd -> pampa(untransformed AST) -> astToPm -> serialize -> pampa -> compare
// Bucket each fixture: exact / equivalent (reformatted) / broken. Prints a findings
// table. See claude-notes/plans/2026-06-23-tiptap-rich-text-block-editor.md.
//
// Run: npx vitest run src/q2-preview/tiptap-roundtrip-spike/roundtrip.test.ts
// (from ts-packages/preview-renderer). Requires a buildable native `pampa`.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { FIXTURES } from './fixtures';
import { parseUntransformed } from './pampa';
import { astToPm } from './astToPm';
import { pmToMarkdown } from './pmToMarkdown';
import { canonical, deepEqual } from './canonical';

type Verdict = 'exact' | 'equivalent' | 'broken';

interface Row {
  name: string;
  verdict: Verdict;
  chips: number;
  unknown: string[];
  mdOut: string;
}

function roundtrip(qmd: string): { row: Omit<Row, 'name'>; } {
  const astIn = parseUntransformed(qmd);
  const { doc, chips, unknown } = astToPm(astIn, qmd);
  const mdOut = pmToMarkdown(doc);
  const astOut = parseUntransformed(mdOut);

  const exact = deepEqual(
    canonical(astIn.blocks, { normalize: false }),
    canonical(astOut.blocks, { normalize: false }),
  );
  const equivalent = deepEqual(
    canonical(astIn.blocks, { normalize: true }),
    canonical(astOut.blocks, { normalize: true }),
  );
  const verdict: Verdict = exact ? 'exact' : equivalent ? 'equivalent' : 'broken';
  return { row: { verdict, chips: chips.length, unknown, mdOut } };
}

describe('tiptap markdown round-trip spike', () => {
  const rows: Row[] = [];

  for (const fx of FIXTURES) {
    it(`round-trips: ${fx.name}`, () => {
      const { row } = roundtrip(fx.qmd);
      rows.push({ name: fx.name, ...row });
      // The spike's purpose is measurement, not a hard gate; we only fail on `broken`
      // so the suite surfaces real regressions while still printing the full table.
      if (row.verdict === 'broken') {
        // eslint-disable-next-line no-console
        console.error(`\nBROKEN: ${fx.name}\n--- qmd ---\n${fx.qmd}\n--- md_out ---\n${row.mdOut}`);
      }
      expect(row.verdict, `${fx.name}: ${row.unknown.join(',')}`).not.toBe('broken');
    });
  }

  it('ZZ prints findings table', () => {
    const pad = (s: string, n: number) => s.padEnd(n);
    const lines = [
      '',
      '=== tiptap round-trip spike — findings ===',
      `${pad('fixture', 24)} ${pad('verdict', 12)} ${pad('chips', 6)} unknown`,
      '-'.repeat(70),
      ...rows.map(
        (r) => `${pad(r.name, 24)} ${pad(r.verdict, 12)} ${pad(String(r.chips), 6)} ${r.unknown.join(',')}`,
      ),
      '-'.repeat(70),
      `exact:      ${rows.filter((r) => r.verdict === 'exact').length}`,
      `equivalent: ${rows.filter((r) => r.verdict === 'equivalent').length}`,
      `broken:     ${rows.filter((r) => r.verdict === 'broken').length}`,
      '',
    ];
    // eslint-disable-next-line no-console
    console.log(lines.join('\n'));

    // Durable evidence artifact: per-fixture qmd -> md_out + verdict.
    const report = [
      '# tiptap round-trip spike — results',
      '',
      '<!-- GENERATED by roundtrip.test.ts (bd-sjb4pzx8). Throwaway spike evidence. -->',
      '',
      `Verdicts: exact=${rows.filter((r) => r.verdict === 'exact').length}, ` +
        `equivalent=${rows.filter((r) => r.verdict === 'equivalent').length}, ` +
        `broken=${rows.filter((r) => r.verdict === 'broken').length}`,
      '',
      ...rows.flatMap((r) => {
        const fx = FIXTURES.find((f) => f.name === r.name)!;
        return [
          `## ${r.name} — \`${r.verdict}\`${r.chips ? ` (${r.chips} chip${r.chips > 1 ? 's' : ''})` : ''}`,
          '',
          '```` qmd in ````',
          fx.qmd.replace(/\n$/, ''),
          '```` md out (PM → markdown) ````',
          r.mdOut.replace(/\n$/, ''),
          '',
        ];
      }),
    ];
    const out = fileURLToPath(new URL('./RESULTS.md', import.meta.url));
    writeFileSync(out, report.join('\n'), 'utf8');
  });
});
