project:
  type: website

website:
  title: "Quarto 2"
  logo: quarto.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - guide/index.qmd
  sidebar:
    - id: guide
      collapse-level: 1
      contents:
        - section: "Guide"
          href: docs/guide/index.qmd

format:
  html:
    theme:
      - cosmo
      # - brand
    css: styles.css
    toc: true
